<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>5dc53dc4-6ffc-44aa-b123-9a2c74aa15f9</UserSecretsId>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CineTrack.Infrastructure\CineTrack.Infrastructure.csproj" />
    </ItemGroup>

</Project>
